class Exercises {
  static const List<String> chestExercises = [
    'Barbell Bench Press',
    'Incline Dumbbell Bench Press',
    'Pec Deck',
    'Cable Crossover',
    'Incline Barbell Bench Press',
    'Dumbbell Bench Press',
    'Dumbbell Fly',
    'Incline Dumbbell Fly',
    'Chest Press Machine',
    'Barbell Declined Bench Press',
    'Dumbbell Declined Bench Press',
    'Push Ups',
  ];

  static const List<String> tricepsExercises = [
    'Lying Triceps Extension',
    'Triceps Pressdown',
    'Cable Rope Pushdown',
    'Dumbbell Overhead Triceps Extension',
    'Close Grip Bench Press',
    'Kickback',
    'Reverse Grip Cable Triceps Extension with Barbell',
    'Single-Arm Cable Triceps Extension',
    'Single-Arm Cable Triceps Extension with Supinated Grip',
    'Lying Dumbbell Triceps Extension',
    'Seated Barbell French Press',
    'Bench Dips',
    'Parallel Dip Bar',
  ];

  static const List<String> calvesExercises = [
    'Seated Calf Raise',
    'Standing Calf Raise',
  ];

  static const List<String> backExercises = [
    'Dumbbell Bent-Over Row (Single Arm)',
    'Wide-Grip Pulldown',
    'Seated Cable Row',
    'Close-Grip Pulldown',
    'Barbell Row',
    'Behind-Neck Pulldown',
    'Reverse-Grip Pulldown',
    'Rope Pulldown',
    'T-Bar Rows',
    'Barbell Bent Over Rows Supinated Grip',
    'Pull Up',
    'Behind the Neck Pull Up',
    'Pull Up with a Supinated Grip',
    'Straight Arm Lat Pulldown',
    'Dumbbell Bent Over Rows',
    'Dumbbell Pullover',
    'Barbell Pullover',
    'Barbell Deadlift',
    'Barbell Sumo Deadlift',
    'Trap Bar Deadlift',
    'Dumbbell Deadlift',
    'Barbell Shrug',
    'Dumbbell Shrugs',
  ];

  static const List<String> bicepsExercises = [
    'Barbell Curl',
    'Alternating Dumbbell Curl',
    'Rope Cable Curl',
    'EZ Barbell Curl',
    'EZ Barbell Preacher Curl',
    'Hammer Curl',
    'Incline Dumbbell Curl',
    'Dumbbell Concentration Curl',
    'Single-Arm Low Pulley Cable Curl',
    'Straight Bar Low Pulley Cable Curl',
    'Standing High Pulley Cable Curl',
    'Seated Barbell Wrist Curl',
    'Seated Barbell Wrist Extension',
    'Reverse Barbell Curl',
  ];

  static const List<String> abdominalsExercises = [
    'Crunch',
    'Oblique Crunch',
    'Crunch Machine',
    'Rope Ab Pulldown',
    'Plank',
    'Hanging Leg Raise',
    'Bent Knee Reverse Crunch',
    'Long Arm Crunch',
    'Plank Get Ups',
  ];

  static const List<String> shouldersExercises = [
    'Dumbbell Shoulder Press',
    'Dumbbell Lateral Raise',
    'Dumbbell Front Raise',
    'High Cable Rear Delt Fly',
    'Smith Machine Shoulder Press',
    'Barbell Upright Row',
    'Bent-Over Lateral Raise',
    'Cable One-Arm Lateral Raise',
    'Dumbbell Push Press',
    'Barbell Push Press',
    'Single-Arm Cable Front Raise',
    'Barbell Front Raise',
    'Seated Barbell Shoulder Press',
    'Seated Behind the Neck Barbell Shoulder Press',
    'Standing Barbell Shoulder Press',
    'Standing Behind the Neck Barbell Shoulder Press',
    'Alternate Dumbbell Front Raise Neutral Grip',
    'One-Arm Low-Pulley Front Raise Neutral Grip',
    'Two-Handed Dumbbell Front Raise',
  ];

  static const List<String> legsExercises = [
    'Squat',
    'Leg Press',
    'Leg Extension',
    'Lunge',
    'Lying Leg Curl',
    'Hack Squat',
    'Seated Leg Curl',
    'Single Leg Extension',
    'Front Squat',
    'Dumbbell Stiff-Leg Deadlift',
    'Barbell Stiff-Leg Deadlift',
    'Dumbbell Goblet Squat',
    'Knee Tuck Jumps',
    'Burpees',
    'Bodyweight Squat',
    '1.5 Rep Bodyweight Squats',
    'Medicine Ball Squat',
    'Barbell Bulgarian Split Squat',
    'Bodyweight Bulgarian Split Squat',
    'Mini-Band Air Squat',
    'Jump Squat',
    'Wall Sit',
    'Medicine Ball Deadlift',
    'Single Leg Bodyweight Deadlift',
    'Kettlebell Sumo Deadlift',
    'Good Morning',
    'Bodyweight Glute Bridge',
    'Single Leg Glute Bridge',
    'Banded Glute Bridge',
    'Duck Walk',
    'Bird Dog',
    'Groiners',
    'Fire Hydrants',
    'Smith Machine Hip Thrust',
    'Barbell Hip Thrust',
    'Band Seated Hip Abduction',
    'Seated Hip Abduction Machine',
    'Standing Cable Abduction',
    'Bodyweight Frog Pump',
    'Smith Machine Frog Pump',
    'Banded Clams',
    'Side Lying Leg Raise',
    'Glute Ham Raise',
    'Dumbbell Step Up',
    'Lateral Mini-Band Walk',
    'Standing Knee Raise',
    'Kettlebell Swings',
    'Standing Cable Kickback',
    'Donkey Kicks',
    'Side Lying Hip Raise',
    'Squat Sit to Reach',
  ];
}
